[versions]
cameraxVersion = "1.4.0-alpha05"
kotlin = "1.8.20"
androidGradlePlugin = "8.0.2"
composeMultiplatformPlugin = "1.4.0"

koin = "3.4.3"

[libraries]
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraxVersion" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraxVersion" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraxVersion" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraxVersion" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version = "1.0.3" } # Version different for who knows what reason


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.8.20" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatformPlugin" }
