package org.picture2pc.picture2pc.presentation.theme

import androidx.compose.ui.graphics.Color

val receiving = Color(0xFF3557C8)
val connected = Color(0xFF2FB86C)
val pending = Color(0xFFFFE921)
val accent = Color(0xFFFF6A00)
val error = Color(0xFFC83538)

val primaryLight = Color(0xFF6635D8)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF7F53F2)
val onPrimaryContainerLight = Color(0xFFFEF8FF)
val secondaryLight = Color(0xFF655399)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC4B0FD)
val onSecondaryContainerLight = Color(0xFF513F84)
val tertiaryLight = Color(0xFF784F84)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAE81BA)
val onTertiaryContainerLight = Color(0xFF3F1A4C)
val errorLight = Color(0xFFA51A23)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFC83538)
val onErrorContainerLight = Color(0xFFFFEBE9)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1D1A23)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1D1A23)
val surfaceVariantLight = Color(0xFFE7DFF4)
val onSurfaceVariantLight = Color(0xFF494455)
val outlineLight = Color(0xFF7A7486)
val outlineVariantLight = Color(0xFFCBC3D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F39)
val inverseOnSurfaceLight = Color(0xFFF5EEFC)
val inversePrimaryLight = Color(0xFFCEBDFF)
val surfaceDimLight = Color(0xFFDED7E5)
val surfaceBrightLight = Color(0xFFFDF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FF)
val surfaceContainerLight = Color(0xFFF2EBF9)
val surfaceContainerHighLight = Color(0xFFECE6F3)
val surfaceContainerHighestLight = Color(0xFFE7E0ED)

val primaryDark = Color(0xFFCEBDFF)
val onPrimaryDark = Color(0xFF390094)
val primaryContainerDark = Color(0xFF7F53F2)
val onPrimaryContainerDark = Color(0xFFFEF8FF)
val secondaryDark = Color(0xFFCEBDFF)
val onSecondaryDark = Color(0xFF362467)
val secondaryContainerDark = Color(0xFF4F3D82)
val onSecondaryContainerDark = Color(0xFFC1ADFA)
val tertiaryDark = Color(0xFFE7B6F2)
val onTertiaryDark = Color(0xFF462153)
val tertiaryContainerDark = Color(0xFFAE81BA)
val onTertiaryContainerDark = Color(0xFF3F1A4C)
val errorDark = Color(0xFFFFB3AE)
val onErrorDark = Color(0xFF68000C)
val errorContainerDark = Color(0xFFC83538)
val onErrorContainerDark = Color(0xFFFFEBE9)
val backgroundDark = Color(0xFF14121B)
val onBackgroundDark = Color(0xFFE7E0ED)
val surfaceDark = Color(0xFF14121B)
val onSurfaceDark = Color(0xFFE7E0ED)
val surfaceVariantDark = Color(0xFF494455)
val onSurfaceVariantDark = Color(0xFFCBC3D7)
val outlineDark = Color(0xFF948EA0)
val outlineVariantDark = Color(0xFF494455)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0ED)
val inverseOnSurfaceDark = Color(0xFF322F39)
val inversePrimaryDark = Color(0xFF6A3ADC)
val surfaceDimDark = Color(0xFF14121B)
val surfaceBrightDark = Color(0xFF3B3842)
val surfaceContainerLowestDark = Color(0xFF0F0D16)
val surfaceContainerLowDark = Color(0xFF1D1A23)
val surfaceContainerDark = Color(0xFF211E28)
val surfaceContainerHighDark = Color(0xFF2B2832)
val surfaceContainerHighestDark = Color(0xFF36333D)

object ConnectionColors {
    val RECEIVING = receiving
    val CONNECTED = connected
    val PENDING = pending
    val DISCONNECTED = error
    val ERROR = error
}